# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  title: Matyushkin D.V.

# Default language
ru:
  languageCode: ru-ru
  contentDir: content/ru
  title: Матюшкин Д.В.
  menu:
    main:
      - name: Обо мне
        url: '#about'
        weight: 10
      - name: Посты
        url: '#posts'
        weight: 20
      - name: Проекты
        url: '#projects'
        weight: 30
      - name: Мероприятия
        url: '#talks'
        weight: 40
      - name: Публикации
        url: '#featured'
        weight: 50
      - name: Контакты
        url: '#contact'
        weight: 60
